ifndef PY_CPPHELP_MAK_INCLUDED
PY_CPPHELP_MAK_INCLUDED=1

ifndef DONT_BUILD_IMPORTS


PY_CPP_DIR=$(ROOT_DIR)/py_cpp
PY_CPP_LIB=$(PY_CPP_DIR)/$(OBJDIR)/py_cpp.lib
PY_CPP_D_LIB=$(PY_CPP_DIR)/$(OBJDIR)/py_cpp_d.lib

$(PY_CPP_LIB) : FORCE
	$(RECURSIVE_MAKE) -C $(PY_CPP_DIR) py_cpp

$(PY_CPP_D_LIB) : FORCE
	$(RECURSIVE_MAKE) -C $(PY_CPP_DIR) py_cpp_d

# end ifndef DONT_BUILD_IMPORTS
endif

# end ifndef PY_CPPHELP_MAK_INCLUDED
endif
