Import("bp_numpy_env")

ufunc_mod = bp_numpy_env.SharedLibrary("ufunc_mod", "ufunc_mod.cpp", SHLIBPREFIX="", 
                                       LIBS="boost_python_numpy")
ufunc_test = bp_numpy_env.PythonUnitTest("ufunc.py", ufunc_mod)

test = ufunc_test
Return("test")
