# -*- python -*-

# Copyright Jim Bosch 2010-2012.
# Distributed under the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

import sys
VERSION = sys.version_info.major
import sysconfig
EXT_SUFFIX = sysconfig.get_config_var("EXT_SUFFIX")

if VERSION == 2 and EXT_SUFFIX == 'None' or EXT_SUFFIX==None:
	EXT_SUFFIX = '.so'
elif VERSION == 3 and EXT_SUFFIX == b'None' or EXT_SUFFIX==None:
	EXT_SUFFIX = '.so'
print ('EXT:', EXT_SUFFIX)

OBJ_SUFFIX = EXT_SUFFIX.replace ('.so', '.os')

Import("env")

LIB_BOOST_NUMPY = ('boost_numpy' + EXT_SUFFIX)
mods = [g.name.replace('.cpp', '') for g in Glob("*.cpp")]
for m in mods:
    env.SharedObject (target=m+OBJ_SUFFIX, source=m+'.cpp')
lib = env.SharedLibrary(LIB_BOOST_NUMPY, source=[m+OBJ_SUFFIX for m in mods])

Return("lib")
