name: Test Windows

on:  [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    env:
      VCPKG_DEFAULT_TRIPLET: 'x64-windows'
      VCPKG_DEFAULT_HOST_TRIPLET: 'x64-windows'
    
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - uses: microsoft/setup-msbuild@v2
    - name: setup boost prerequisites
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        runVcpkgInstall: true
        vcpkgJsonGlob: .github/workflows/vcpkg.json
        vcpkgArguments: '--x-manifest-root=${{ github.workspace }}/vcpkg'
    - name: List directory contents
      run: Get-ChildItem -Path "${{ github.workspace }}/vcpkg" -Recurse -Force -File -Filter 'config.hpp'
      shell: pwsh
    - name: setup faber
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools faber numpy
        faber --info=tools cxx
    - name: build
      shell: cmd
      run: |
        faber --builddir=build cxx.name=msvc --log=commands --log=output --with-boost-include=${{ github.workspace }}\vcpkg\installed\x64-windows\include -j4
    - name: test
      shell: cmd
      run: |
        faber --builddir=build cxx.name=msvc --with-boost-include=${{ github.workspace }}\vcpkg\installed\x64-windows\include -j4 test.report
