name: Test Windows

on:  [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python: [python3]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: warrenbuckley/setup-vswhere@v1
    - uses: actions/setup-python@v2
    - name: setup boost prerequisites
      uses: lukka/run-vcpkg@v6
      with:
        #vcpkgArguments: boost:x64-windows
        vcpkgGitCommitId: '8a9a97315aefb3f8bc5d81bf66ca0025938b9c91'

    - name: setup faber
      shell: 'bash'
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools faber
    - name: build
      shell: 'bash'
      run: |
        faber -v
        sed -e "s/\$PYTHON/python/g" .ci/faber > ~/.faber
        faber --info=tools cxx
        faber \
          --builddir=build \
          cxx.name=msvc
    - name: test
      shell: 'bash'
      run: |
        faber \
          --builddir=build \
          cxx.name=msvc \
          test.report
